import turtle 
import time 
from turtle import *

pen = turtle.Turtle()

pen2=turtle.Turtle()
win = turtle.Screen()
win.setup(800,580)
win.bgpic("spong.gif")
pen.speed(0)

turtle.colormode(255)

def buttonclick(x,y):
    print("You clicked at this coordinate({0},{1})".format(x,y))

def halfcircle(parts=360, line=1, direction=1):
    for x in range(parts//2):
      
        pen.forward(line)
        pen.left(200/parts * direction)


def handsdown():
    tracer(0,0)
    pen2.up()
    pen2.goto(-124.0,-38.0)
    pen2.down()
    pen2.color("white")
    pen2.pencolor("black")
    pen2.width(3)
    pen2.begin_fill()
    pen2.setheading(200)
    pen2.circle(50,50)
    pen2.setheading(320)
    pen2.fd(30)
    pen2.setheading(30)
    pen2.fd(10)
    pen2.end_fill()
    pen2.up()
    pen2.goto(-148.0,-74.0)
    pen2.color("#ffff44")
    pen2.pencolor("black")
    pen2.begin_fill()
    pen2.setheading(230)
    pen2.down() 
    pen2.fd(60)
    pen2.setheading(160)
    pen2.circle(20,40)
    pen2.setheading(160)
    pen2.fd(10)
    pen2.circle(7,150)
    pen2.setheading(350)
    pen2.fd(20)
    pen2.setheading(210)
    pen2.fd(20)
    pen2.circle(7,150)
    pen2.setheading(40)
    pen2.fd(20)
    pen2.setheading(250)
    pen2.fd(17)
    pen2.setheading(250)
    pen2.circle(7,150)
    pen2.setheading(80)
    pen2.fd(20)
    pen2.setheading(290)
    pen2.fd(15)
    pen2.setheading(290)
    pen2.circle(7,150)
    pen2.setheading(120)
    pen2.fd(15)
    pen2.setheading(30)
    pen2.circle(10,100)
    pen2.setheading(50)
    pen2.fd(60)
    pen2.end_fill()
    update()

def handsup():
    tracer(0,0)
    pen2.up()
    pen2.goto(-124.0,-38.0)
    pen2.down()
    pen2.color("white")
    pen2.pencolor("black")
    pen2.width(3)
    pen2.begin_fill()
    pen2.setheading(180)
    pen2.fd(40)
    pen2.setheading(100)
    pen2.fd(30)
    pen2.setheading(30)
    pen2.circle(-50,50)
    pen2.end_fill()
    pen2.up()
    pen2.goto(-170.0,-15.0)
    pen2.color("#ffff44")
    pen2.pencolor("black")
    pen2.begin_fill()
    pen2.setheading(190)
    pen2.down() 
    pen2.fd(60)
    pen2.setheading(140)
    pen2.circle(20,40)
    pen2.setheading(140)
    pen2.fd(10)
    pen2.circle(7,150)
    pen2.setheading(330)
    pen2.fd(20)
    pen2.setheading(180)
    pen2.fd(20)
    pen2.circle(7,150)
    pen2.setheading(10)
    pen2.fd(20)
    pen2.setheading(220)
    pen2.fd(17)
    pen2.setheading(220)
    pen2.circle(7,150)
    pen2.setheading(50)
    pen2.fd(20)
    pen2.setheading(260)
    pen2.fd(15)
    pen2.setheading(260)
    pen2.circle(7,150)
    pen2.setheading(90)
    pen2.fd(20)
    pen2.setheading(350)
    pen2.circle(8,100)
    pen2.setheading(13)
    pen2.fd(58)
    pen2.end_fill()
    update()
          
def oval(r):               
    for loop in range(2):
        pen.circle(r,90)
        pen.circle(r/2,90)        
        
def talloval(r):               
    pen.left(45)
    for loop in range(2):      
        pen.circle(r,90)    
        pen.circle(r/2,90)     

# draw the white shirt
pen.up()
pen.goto(65,-65)
pen.down()
pen.color("white")
pen.pencolor("black")
pen.width(3)
pen.begin_fill()
pen.setheading(260)
pen.fd(32)
pen.setheading(180)
pen.fd(176)
pen.setheading(100)
pen.fd(32)
pen.end_fill()

# draw nick
pen.up()
pen.goto(-30.0,-64.0)
pen.down()
for i in range(2):
    pen.color("white")
    pen.pencolor("black")
    pen.begin_fill()
    pen.setheading(230)
    pen.fd(25)
    pen.setheading(130)
    pen.fd(25)
    pen.end_fill()
    pen.up()
    pen.setheading(0)
    pen.fd(80)
    pen.down()

# draw the brown shirt
pen.up()
pen.goto(59,-95)
pen.down()
pen.color("#cc860e")
pen.pencolor("black")
pen.width(3)
pen.begin_fill()
pen.setheading(260)
pen.fd(35)
pen.setheading(180)
pen.fd(164)
pen.setheading(100)
pen.fd(35)
pen.end_fill()
pen.setheading(0)
pen.fd(175)
# draw the black rectangles
pen.up()
pen.goto(-108,-102)
pen.down()
for i in range(4):
    pen.color("black")
    pen.pencolor("black")
    pen.begin_fill()
    pen.setheading(0)
    pen.fd(25)
    pen.setheading(270)
    pen.fd(5)
    pen.setheading(180)
    pen.fd(25)
    pen.setheading(90)
    pen.fd(5)
    pen.setheading(0)
    pen.end_fill()
    if i == 1: 
        pen.up()
        pen.fd(30)
        pen.down()
    pen.up()
    pen.fd(35)
    pen.down()
# draw the tie
pen.up()
pen.goto(-25,-60)
pen.down()
pen.color("#ff0000")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(300)
pen.fd(34)
pen.setheading(240)
pen.fd(30)
pen.setheading(120)
pen.fd(30)
pen.setheading(60)
pen.fd(34)
pen.end_fill()
# draw the tie top
pen.up()
pen.goto(-14,-70)
pen.down()
pen.color("#ff0000")
pen.pencolor("black")
pen.begin_fill()
talloval(15)
pen.end_fill()

# right hand
pen.up()
pen.goto(77.0,-38.0)
pen.down()
pen.color("white")
pen.pencolor("black")
pen.width(3)
pen.begin_fill()
pen.setheading(340)
pen.circle(-50,50)
pen.setheading(220)
pen.fd(30)
pen.setheading(150)
pen.fd(40)
pen.end_fill()
pen.up()
pen.goto(102.0,-71.0)
pen.down()
pen.color("#ffff44")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(320)
pen.fd(60)
pen.setheading(30)
pen.circle(-20,40)
pen.setheading(30)
pen.fd(10)
pen.circle(-7,150)
pen.setheading(200)
pen.fd(20)
pen.setheading(340)
pen.fd(20)
pen.circle(-7,150)
pen.setheading(150)
pen.fd(20)
pen.setheading(300)
pen.fd(17)
pen.setheading(300)
pen.circle(-7,150)
pen.setheading(110)
pen.fd(20)
pen.setheading(250)
pen.fd(15)
pen.setheading(250)
pen.circle(-7,150)
pen.setheading(55)
pen.fd(15)
pen.setheading(170)
pen.circle(-10,100)
pen.setheading(138)
pen.fd(60)
pen.end_fill()

# draw the face outline
pen.penup()
pen.goto(-100,150)
pen.pendown()

pen.color("#ffff44")
pen.pencolor("black")
pen.begin_fill()

for i  in range(4):
    pen.setheading(315)

    halfcircle(13, 360/80, 1)
    halfcircle(13, 360/80, -1)

for i  in range(4):
    pen.setheading(310)
    halfcircle(15, 360/80, -1)
    halfcircle(15, 360/80, 1)

for i  in range(4):
    pen.setheading(225)
    halfcircle(13, 360/80, -1)
    halfcircle(13, 360/80, 1)

for i  in range(4):
    pen.setheading(50)
    halfcircle(15, 360/80, 1)
    halfcircle(15, 360/80, -1)

pen.setheading(40)
halfcircle(13, 360/80, -1)
halfcircle(13, 360/80, 1)

pen.end_fill()

# draw the lashes
pen.up()
pen.goto(-10,99)
pen.down()
pen.width(2)

for i in range (3):
    pen.color("black")
    pen.begin_fill()
    pen.setheading(90)
    pen.fd(15)
    pen.setheading(0)
    pen.fd(1)
    pen.setheading(270)
    pen.fd(15)
    pen.end_fill()
    pen.up()
    pen.setheading(0)
    pen.fd(15)
    pen.down()
    

pen.up()
pen.goto(-80,99)
pen.down()

for i in range (3):
    pen.color("black")
    pen.begin_fill()
    pen.setheading(90)
    pen.fd(15)
    pen.setheading(0)
    pen.fd(1)
    pen.setheading(270)
    pen.fd(15)
    pen.end_fill()
    pen.up()
    pen.setheading(0)
    pen.fd(15)
    pen.down()

# big eyes
pen.penup()
pen.goto(-100,70)
pen.setheading(270)
pen.pendown()
pen.pensize(3)
pen.color("white")
pen.pencolor("black")
pen.begin_fill()
pen.circle(35)
pen.penup()
pen.setheading(0)
pen.fd(72)
pen.down()
pen.setheading(270)
pen.circle(35)
pen.end_fill()
# blue eye
pen.color("#99ccff")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(0)
pen.up()
pen.fd(20)
pen.right(90)
pen.down()
pen.circle(15)
pen.up()
pen.setheading(180)
pen.fd(40)
pen.right(90)
pen.down()
pen.circle(15)
pen.end_fill()
# small black eye
pen.color("black")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(180)
pen.up()
pen.fd(10)
pen.right(90)
pen.down()
pen.circle(5)
pen.up()
pen.setheading(0)
pen.fd(60)
pen.right(90)
pen.down()
pen.circle(5)
pen.end_fill()
# draw the nose
pen.penup()
pen.goto(-20,50)
pen.down()

pen.color("#ffff44")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(90)
pen.circle(12,260)
pen.end_fill()
# draw the mouse
pen.up()
pen.goto(-110,50)
pen.down()
pen.setheading(270)
pen.circle(50,70)
pen.fd(10)
pen.setheading(-1)
pen.fd(5)
pen.setheading(0)
pen.fd(70)
pen.setheading(15)
pen.fd(15)
pen.setheading(30)
pen.circle(50,70)

pen.up()
pen.goto(-5,0)
pen.down()

# draw the teeth
pen.color("white")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(290)
pen.fd(15)
pen.setheading(180)
pen.fd(20)
pen.setheading(105)
pen.fd(15)
pen.end_fill()

pen.setheading(180)
pen.up()
pen.fd(10)
pen.down()

pen.color("white")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(250)
pen.fd(15)
pen.setheading(180)
pen.fd(20)
pen.setheading(70)
pen.fd(15)
pen.end_fill()

#draw green circles
m=0
for i in range(2):
    
    pen.up()
    pen.goto(70+m,120)
    pen.down()

    pen.color("#98be0e")
    pen.begin_fill()
    talloval(20)
    pen.end_fill()
    pen.left(-40)
    m+=-160

n=0
for i in range(2):
    
    pen.up()
    pen.goto(25+n,125)
    pen.down()

    pen.color("#98be0e")
    pen.begin_fill()
    oval(8)
    pen.end_fill()
    n+=-95
x=0
for i in range(2):
    
    pen.up()
    pen.goto(50+x,-30)
    pen.down()
    
    pen.color("#98be0e")
    pen.begin_fill()
    talloval(20)
    pen.end_fill()
    pen.left(-45)
    x+=-125

y=0
for i in range(2):
    
    pen.up()
    pen.goto(15+y,-50)
    pen.down()

    pen.color("#98be0e")
    pen.begin_fill()
    oval(8)
    pen.end_fill()
    y+=-70

pen.up()
pen.goto(-65.0,-130.0)
pen.down()
for i in range(2):
    pen.color("#cc860e")
    pen.pencolor("black")
    pen.begin_fill()
    pen.setheading(270)
    pen.fd(10)
    pen.setheading(0)
    pen.fd(30)
    pen.setheading(90)
    pen.fd(10)
    pen.end_fill()
    pen.up()
    pen.setheading(0)
    pen.fd(20)
    pen.down()

pen.up()
pen.goto(-55.0,-141.0)
pen.down()
# deaw the legs
for i in range(2):
    pen.color("#ffff44")
    pen.pencolor("black")
    pen.begin_fill()
    pen.setheading(270)
    pen.fd(22)
    pen.setheading(0)
    pen.fd(10)
    pen.setheading(90)
    pen.fd(22)
    pen.end_fill()
    pen.up()
    pen.setheading(0)
    pen.fd(40)
    pen.down()
pen.up()
pen.goto(-55.0,-166.0)
pen.down()
#draw the socks
for i in range(2):
    pen.color("white")
    pen.pencolor("black")
    pen.begin_fill()
    pen.setheading(270)
    pen.fd(30)
    pen.setheading(0)
    pen.fd(10)
    pen.setheading(90)
    pen.fd(30)
    pen.end_fill()
    pen.up()
    pen.setheading(0)
    pen.fd(40)
    pen.down()

pen.up()
pen.goto(-54.0,-164.0)
pen.down()
#draw socks lines
for i in range(2):
    pen.pencolor("black")
    pen.setheading(0)
    pen.fd(9)
    pen.setheading(270)
    pen.up()
    pen.fd(9)
    pen.down()
    pen.pencolor("blue")
    pen.setheading(180)
    pen.fd(9)
    pen.setheading(270)
    pen.up()
    pen.fd(5)
    pen.down()
    pen.pencolor("red")
    pen.setheading(0)
    pen.fd(9)
    if (i == 0):
        pen.up()
        pen.goto(-5.0,-165.0)
        pen.down()
# draw the shoe
pen.up()
pen.goto(-55.0,-196.0)
pen.down()
pen.color("black")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(180)
pen.circle(30,30)
pen.right(55)
oval(20)
pen.setheading(270)
pen.fd(20)
pen.setheading(0)
pen.circle(25,30)
pen.setheading(270)
pen.fd(8)
pen.setheading(0)
pen.fd(13)
pen.setheading(90)
pen.fd(32)
pen.end_fill()

pen.up()
pen.goto(4.0,-196.0)
pen.down()
pen.color("black")
pen.pencolor("black")
pen.begin_fill()
pen.setheading(0)
pen.circle(-30,30)
pen.right(300)
oval(-20)
pen.setheading(270)
pen.fd(20)
pen.setheading(180)
pen.circle(-25,30)
pen.setheading(270)
pen.fd(8)
pen.setheading(180)
pen.fd(13)
pen.setheading(90)
pen.fd(32)
pen.end_fill()

pen.up()
pen.goto(-80.0,-205.0)
pen.down()
# shoe white spots
pen.color("white")
pen.pencolor("white")
pen.begin_fill()
pen.circle(4)

pen.end_fill()

pen.up()
pen.setheading(0)
pen.fd(5)
pen.down()

pen.color("white")
pen.pencolor("white")
pen.begin_fill()
pen.circle(1)

pen.end_fill()


pen.up()
pen.goto(30.0,-206.0)
pen.down()

pen.color("white")
pen.pencolor("white")
pen.begin_fill()
pen.circle(1)
pen.end_fill()
pen.hideturtle()
# animated hand
pen2.hideturtle()
for i in range(10):
    pen2.clear()
    handsdown()
    time.sleep(0.5)
    pen2.clear()
    handsup()
    time.sleep(0.5)

turtle.onscreenclick(buttonclick,1)
turtle.listen()

win.mainloop()